export const SET_USERS = 'SET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const LOAD_TRANSACTIONS_ERROR = 'LOAD_TRANSACTIONS_ERROR';
export const CREATE_TRANSACTION ='CREATE_TRANSACTION';
export const REMOVE_TRANSACTION ='REMOVE_TRANSACTION';
export const UPDATE_TRANSACTION ='UPDATE_TRANSACTION';